grails-app/controllers/com/webverticaldomains/SecureController.groovy
package com.webverticaldomains

import com.webverticaldomains.auth.Role
import com.webverticaldomains.auth.User
import com.webverticaldomains.auth.UserRole
import grails.converters.JSON

class SecureController {

    def index() {
        //render 'security access only'
        render view: 'index'
    }

    def createUser() {
        render(view: 'registerUser')
    }
    def enterCategory(){
        render(view: 'saveCategory')
    }

    def saveCategory(){
        def categoryInstance = new Category(name: params.name)
        if (params.actualParentCat) {
            def parentCategory = Category.get(params.actualParentCat as long)
            categoryInstance.parentCategory = parentCategory
        }
        categoryInstance = categoryInstance.save()
        flash.message = "Category <b>$categoryInstance.name</b> successfully created."
        redirect(action: 'enterCategory')
    }

    def createSubCat() {
        def category = Category.get(params.catId as long)
        def subCats = Category.findAllByParentCategory(category)
        if(subCats?.size())
            render(template: 'subCategory', model: [subCats: subCats, catId: params.catId])
        else
            render(text: '')
    }

    def registerUser() {
        def isAjax = params.getBoolean('ajaxRequest', false)
        def userInstance = new User(
            username:  params.username,
            password:  params.password,
            email:  params.email
        )
        userInstance.save()
        if (userInstance?.hasErrors()) {
            if (isAjax) {
                def errors = [:]
                userInstance.errors.fieldErrors.each { errors << [(it.field): it.defaultMessage] }
                render([errors: errors, success: false] as JSON)
            } else {
                flash.error = userInstance.errors.fieldErrors.each { "${it.field}: ${it.defaultMessage}" }.join("<br />")
                render(view: 'registerUser')
            }
        } else if (userInstance?.id) {
            UserRole.create userInstance, Role.findByAuthority("ROLE_USER"), true
            if (isAjax)
                render([message: "Please check your email for activation email", success: true] as JSON)
            else
                redirect(controller: 'login', action: 'auth')
        }
    }

    def createProduct() {
        render(view: 'createProduct')
    }

    def saveProduct() {
        def category = Category.get(params.actualParentCat as long)
        def product = new Product(category: category)
        bindData(product, params)
        if (! product.validate()) {
            flash.error = product.errors.fieldErrors.each { "${it.field}: ${it.defaultMessage}" }.join("<br />")
            redirect(action: 'createProduct')
            return
        }
        product.save(validate: false, flush: true)
        def files = request.getFiles("productImages")
        if(files?.size() && files[0].fileItem.size > 0) {
            files?.each {
                def file = new Image(file: it, name: it.originalFilename, type: it.contentType)
                if (file.save())
                    product.addToImages(file)
            }
        }
        redirect(action: 'createProduct')
    }
}

grails-app/views/secure/_subCategory.gsp
<g:select name="subCategory${catId}" class="category" from="${subCats}" optionKey="id" optionValue="name" noSelection="['':'Select']"/>
<div id="subCatDiv${catId}"></div>
<script>
    registerCategoryOnChange("subCategory${catId}", "subCatDiv${catId}");
</script>

grails-app/views/secure/createCategory.gsp
<%--
  Created by IntelliJ IDEA.
  User: Preethivar
  Date: 19/2/14
  Time: 4:20 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Add Category</title>
  <meta name='layout' content='main' />
</head>
<body>
    <g:form controller="secure" action="createCategory">
        <fieldset>
            <div class="clearfix" id="parentCategoryDiv">
                <g:select name="parentCategory" class="mainCategory" from="${com.webverticaldomains.Category.findAllByParentCategoryIsNull()}"
                          optionKey="id" optionValue="name"
                          noSelection="['':'Main']" onchange="catChanged('parentCategory', 'subCatDiv')"/><br/>
                <span id="subCatDiv"></span>
                <input name="actualParentCat" id="actualParentCat" type="hidden" value=""/>
            </div>
            <label class="block clearfix">
                <span class="input-icon input-icon-right">
                    <g:textField class="form-control" placeholder="Name" name="name" />
                    <i class="icon-envelope"></i>
                </span>
            </label>
            <div class="clearfix">
                <button type="submit" class="btn btn-sm btn-success">
                    Create
                    <i class="icon-arrow-right icon-on-right"></i>
                </button>
            </div>
        </fieldset>
    </g:form>
<g:javascript>
    function catChanged(selectId, divId) {
        var catID = $("#"+selectId).val();
        if(catID!="" && catID!=null)
            $("#actualParentCat").val(catID);
        else
            $("#actualParentCat").val($("#"+selectId).parent().parent().find('select').val());
        if(catID != '' && catID != null) {
            $.ajax({
                url: "${createLink(controller: 'secure', action: 'createSubCat')}",
                type:"post",
                data: {catId: catID},
                success: function(data) {
                    if(data != '' && data != null) {
                        $("#"+divId).empty();
                        $("#"+divId).append(data);
                    } else {
                        $("#"+divId).empty();
                    }
                },
                error: function(xhr){
                    alert(xhr.responseText);
                }
            });
        } else  $("#"+divId).empty();
    }
    function registerCategoryOnChange(selectId, divId) {
        $("#"+selectId).on('change', function(){
            if($(this).val()!="" && $(this).val()!=null)
                $("#actualParentCat").val($(this).val());
            else
                $("#actualParentCat").val($(this).parent().parent().find('select').val());
            var divId = $(this).parent().find('div').attr('id');
            catChanged($(this).attr('id'), divId);
        });
    }
</g:javascript>
</body>
</html>

grails-app/views/secure/createProduct.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Create Product Page</title>
    <meta name="layout" content="secure_main"/>
</head>
<body>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="widget-box transparent invoice-box">
            <div class="widget-header widget-header-large">
                <h3 class="grey lighter pull-left position-relative">
                    <i class="icon-leaf green"></i>
                    Create Product
                </h3>
            </div>
            <div class="widget-body">
                <div class="widget-main padding-24">
                    <div class="row">
                        <g:if test="${flash.error}">
                            ${flash.error}
                        </g:if>
                        <g:form action="saveProduct" method="post" name="createProduct"
                                enctype="multipart/form-data" onsubmit="return checkCategorySelected()">
                            <div class="form-group" style="float: none; display: block; clear: both; padding: 1px 0px;">
                                <label class="col-sm-3 control-label no-padding-right">Category:</label>
                                <div class="col-sm-9">
                                    <g:select name="parentCategory" class="mainCategory" from="${com.webverticaldomains.Category.findAllByParentCategoryIsNull()}"
                                              optionKey="id" optionValue="name"
                                              noSelection="['':'Select']" onchange="catChanged('parentCategory', 'subCatDiv')"/><br/>
                                    <span id="subCatDiv"></span>
                                    <input name="actualParentCat" id="actualParentCat" type="hidden" value=""/>
                                </div>
                            </div>
                            <div class="form-group" style="float: none; display: block; clear: both; padding: 1px 0px;">
                                <label class="col-sm-3 control-label no-padding-right">Name:</label>
                                <div class="col-sm-9">
                                    <g:textField name="name" class='input-large text_' placeholder="Product Name" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Price:</label>
                                <div class="col-sm-9">
                                    <g:textField name="price" class='input-large text_' placeholder="Product Price" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Reduced Price(Optional):</label>
                                <div class="col-sm-9">
                                    <g:textField name="reducedPrice" class='input-large text_' placeholder="Product Reduced Price" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Manufacturer:</label>
                                <div class="col-sm-9">
                                    <g:textField name="manufacturer" class='input-large text_' placeholder="Manufacturer of Product" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Brief Description:</label>
                                <div class="col-sm-9">
                                    <g:textField name="briefDesc" class='input-large text_' placeholder="Product Brief Description" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Detailed Description:</label>
                                <div class="col-sm-9">
                                    <g:textArea name="detailDesc" class='input-large text_' placeholder="Product Detailed Description" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right">Image Files(max 5):</label>
                                <div class="col-sm-9">
                                    <input type="file" accept="image/*" name="productImages" id="productImages" multiple="true" max="5" class='input-large file_' placeholder="Product Images" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"></label>
                                <div class="col-sm-9">
                                    <g:submitButton name="save" value="Save" class="btn btn-info btn-sm">
                                        <i class="icon-key bigger-110"></i>
                                        Save
                                    </g:submitButton>
                                </div>
                            </div>
                        </g:form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
        .form-group {
            float: none !important;
            display: block;
            clear: both !important;
            padding: 1px 0px;
        }
        .form-group:after, .form-group:before {
            clear: both;
            content: "";
            display: block;
        }
    </style>
    <g:javascript>
        function catChanged(selectId, divId) {
            var catID = $("#"+selectId).val();
            if(catID!="" && catID!=null)
                $("#actualParentCat").val(catID);
            else
                $("#actualParentCat").val($("#"+selectId).parent().parent().find('select').val());
            if(catID != '' && catID != null) {
                $.ajax({
                    url: "${createLink(controller: 'secure', action: 'createSubCat')}",
                    type:"post",
                    data: {catId: catID},
                    success: function(data) {
                        if(data != '' && data != null) {
                            $("#"+divId).empty();
                            $("#"+divId).append(data);
                        } else {
                            $("#"+divId).empty();
                        }
                    },
                    error: function(xhr){
                        alert(xhr.responseText);
                    }
                });
            } else  $("#"+divId).empty();
        }
        function registerCategoryOnChange(selectId, divId) {
            $("#"+selectId).on('change', function(){
                if($(this).val()!="" && $(this).val()!=null)
                    $("#actualParentCat").val($(this).val());
                else
                    $("#actualParentCat").val($(this).parent().parent().find('select').val());
                var divId = $(this).parent().find('div').attr('id');
                catChanged($(this).attr('id'), divId);
            });
        }
        function checkCategorySelected() {
            if($("#actualParentCat").val() == '' || $("#actualParentCat").val() == null) {
                alert("Select a category");
                return false;
            } else return true;
        }
    </g:javascript>
</body>
</html>

grails-app/views/secure/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Admin Pages</title>
  <meta name='layout' content='secure_main' />
</head>
<body>
<div class="col-sm-10 col-sm-offset-1">
    <div class="widget-box transparent invoice-box">
        <div class="widget-header widget-header-large">
            <h3 class="grey lighter pull-left position-relative">
                <i class="icon-leaf green"></i>
                Admin Pages
            </h3>
        </div>
        <div class="widget-body">
            <div class="widget-main padding-24">
                <div class="row">
                    <sec:ifAnyGranted roles="ROLE_ADMIN">
                        <g:link action="enterCategory">Create Category</g:link><br /><br />
                        <g:link action="createProduct">Create Product</g:link>
                    </sec:ifAnyGranted>
                    <sec:ifNotGranted roles="ROLE_ADMIN">security access only</sec:ifNotGranted>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/secure/listProducts.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <meta name="layout" content="main"/>
  <title>
        Listing Products
  </title>

</head>
<body>
    <g:each in="${products}" var="product">
    <div class="top_prod_box"></div>
    <div class="center_prod_box">
        <div class="product_title"><a href="${createLink(controller: 'product', action: 'details', params: [id: product.id])}" id="${product.name}"></a></div>
        <div class="product_img">
            <a href="${createLink(controller: 'product', action: 'details', params: [id: product.id])}">
                %{--<img src="${createLink(controller: 'product', action: 'productImage', params:[/*productId: product.id,*/ imageId: product.images?.asList()?.first()?.id])}" alt="" border="0" style="max-height: 75px; max-width: 75px;" /></a>--}%
        </div>
        <div class="prod_price"><g:if test="${product.reducedPrice}"><span class="reduce">${product.price}$</span> </g:if><span class="price">${product.reducedPrice?:product.price}$</span></div>
        <div class="bottom_prod_box"></div>
        <div class="prod_details_tab">
            <a href="#" title="header=[Add to cart] body=[&nbsp;] fade=[on]"><img src="images/cart.gif" alt="" border="0" class="left_bt" /></a>
            <a href="#" title="header=[Specials] body=[&nbsp;] fade=[on]"><img src="images/favs.gif" alt="" border="0" class="left_bt" /></a>
            <a href="#" title="header=[Gifts] body=[&nbsp;] fade=[on]"><img src="images/favorites.gif" alt="" border="0" class="left_bt" /></a>
            <a href="${createLink(controller: 'product', action: 'details', params: [id: product.id])}" class="prod_details">details</a>
        </div>
    </div>
</g:each>
</body>
</html>

grails-app/views/secure/registerUser.gsp
<%@ page import="grails.plugin.springsecurity.LoginController" contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Please Register</title>
</head>
<body>
    <g:if test="${flash.error}">
        ${flash.error}
    </g:if>
    <g:formRemote name="register" url="${[action: 'registerUser']}">
        Username<input type="text" name="username"><br />
        Password<input type="password" name="password"><br />
        Email Address<input type="text" name="email"><br />
        <g:submitButton name="submit" value="Submit" />
    </g:formRemote>
</body>
</html>

grails-app/views/secure/saveCategory.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Add Category</title>
  <meta name='layout' content='secure_main' />
</head>
<body>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <g:if test="$flash.message">
            <div style="text-align: center">
                <span class="label label-success">${flash.message}</span>
            </div>
        </g:if>
        <div class="widget-box transparent invoice-box">
            <div class="widget-header widget-header-large">
                <h3 class="grey lighter pull-left position-relative">
                    <i class="icon-leaf green"></i>
                    Create Category
                </h3>
            </div>
            <div class="widget-body">
                <div class="widget-main padding-24">
                    <div class="row">
                        <g:if test="${flash.error}">
                            ${flash.error}
                        </g:if>
                        <g:form controller="secure" action="saveCategory" enctype="multipart/form-data">
                            <div class="form-group" style="float: none; display: block; clear: both; padding: 1px 0px;">
                                <label class="col-sm-3 control-label no-padding-right">Parent Category:</label>
                                <div class="col-sm-9">
                                    <g:select name="parentCategory" class="mainCategory" from="${com.webverticaldomains.Category.findAllByParentCategoryIsNull()}"
                                              optionKey="id" optionValue="name"
                                              noSelection="['':'Main']" onchange="catChanged('parentCategory', 'subCatDiv')"/><br/>
                                    <span id="subCatDiv"></span>
                                    <input name="actualParentCat" id="actualParentCat" type="hidden" value=""/>
                                </div>
                            </div>
                            <div class="form-group" style="float: none; display: block; clear: both; padding: 1px 0px;">
                                <label class="col-sm-3 control-label no-padding-right">Name:</label>
                                <div class="col-sm-9">
                                    <g:textField class="form-control" placeholder="Name" name="name" />
                                </div>
                            </div>
                            <div class="form-group" style="float: none; display: block; clear: both; padding: 1px 0px;">
                                <label class="col-sm-3 control-label no-padding-right"> </label>
                                <div class="col-sm-9">
                                    <g:submitButton name="save" value="Save" class="btn btn-info btn-sm">
                                        <i class="icon-key bigger-110"></i>
                                        Save
                                    </g:submitButton>
                                </div>
                            </div>
                        </g:form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type="text/css">
    .form-group:after, .form-group:before {
        clear: both;
        content: "";
        display: block;
    }
    </style>
<g:javascript>
    function catChanged(selectId, divId) {
        var catID = $("#"+selectId).val();
        if(catID!="" && catID!=null)
            $("#actualParentCat").val(catID);
        else
            $("#actualParentCat").val($("#"+selectId).parent().parent().find('select').val());
        if(catID != '' && catID != null) {
            $.ajax({
                url: "${createLink(controller: 'secure', action: 'createSubCat')}",
                type:"post",
                data: {catId: catID},
                success: function(data) {
                    if(data != '' && data != null) {
                        $("#"+divId).empty();
                        $("#"+divId).append(data);
                    } else {
                        $("#"+divId).empty();
                    }
                },
                error: function(xhr){
                    alert(xhr.responseText);
                }
            });
        } else  $("#"+divId).empty();
    }
    function registerCategoryOnChange(selectId, divId) {
        $("#"+selectId).on('change', function(){
            if($(this).val()!="" && $(this).val()!=null)
                $("#actualParentCat").val($(this).val());
            else
                $("#actualParentCat").val($(this).parent().parent().find('select').val());
            var divId = $(this).parent().find('div').attr('id');
            catChanged($(this).attr('id'), divId);
        });
    }
</g:javascript>
</body>
</html>